version: '2.0'
services: 
    web:
        build: .
        ports:
            - 3000:3000
        volumes: 
            - ${PWD}:/app
        environment:
            - NODE_ENV=development
        stdin_open: true
